// Auto-generated by scripts/generate-plugin-registry.mjs
// Nicht manuell bearbeiten.

import type { ComponentType, LazyExoticComponent } from 'react';


export interface PluginRoute {
    path: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
}

export interface PluginNavItem {
    label: string;
    icon: string;
    path: string;
    permission?: string;
    order: number;
    group?: string;
    groupIcon?: string;
    groupOrder?: number;
}

export interface PluginDashboardTile {
    id: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    defaultSize?: 'small' | 'medium' | 'large';
    defaultVisible?: boolean;
}

export interface PluginExtensionTile {
    id: string;
    targetSlot: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    defaultSize?: 'small' | 'medium' | 'large';
}

export interface PluginSettingsPanel {
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
}

export interface PluginSearchResult {
    title: string;
    description?: string;
    path: string;
    icon?: string;
}

export interface PluginSearchProvider {
    label: string;
    search: (query: string) => Promise<PluginSearchResult[]>;
    permission?: string;
}

export interface PluginQuickAction {
    id: string;
    label: string;
    icon?: string;
    keywords?: string[];
    permission?: string;
    execute: () => void | Promise<void>;
}

export interface PluginRegistryEntry {
    id: string;
    name: string;
    routes: PluginRoute[];
    navItems: PluginNavItem[];
    dashboardTiles: PluginDashboardTile[];
    extensionTiles: PluginExtensionTile[];
    settingsPanel?: PluginSettingsPanel;
    searchProvider?: PluginSearchProvider;
    quickActions?: PluginQuickAction[];
}

export const pluginRegistry: PluginRegistryEntry[] = [

];
