// Auto-generated by scripts/generate-plugin-registry.mjs
// Nicht manuell bearbeiten.

import type { ComponentType, LazyExoticComponent } from 'react';
import * as plugin_todo_0 from '../../plugins/todo/frontend/index.tsx';

export interface PluginRoute {
    path: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
}

export interface PluginNavItem {
    label: string;
    icon: string;
    path: string;
    permission?: string;
    order: number;
    group?: string;
    groupIcon?: string;
    groupOrder?: number;
}

export interface PluginDashboardTile {
    id: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    /** @deprecated Verwende defaultWidth/defaultHeight. Wird automatisch migriert. */
    defaultSize?: 'small' | 'medium' | 'large';
    /** Breite in Grid-Units (1 Unit = 20px). Default: 12 */
    defaultWidth?: number;
    /** Höhe in Grid-Units (1 Unit = 20px). Default: 8 */
    defaultHeight?: number;
    defaultVisible?: boolean;
}

export interface PluginExtensionTile {
    id: string;
    targetSlot: string;
    title: string;
    description?: string;
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
    order?: number;
    defaultSize?: 'small' | 'medium' | 'large';
}

export interface PluginSettingsPanel {
    component: LazyExoticComponent<ComponentType<any>>;
    permission?: string;
}

export interface PluginSearchResult {
    title: string;
    description?: string;
    path: string;
    icon?: string;
}

export interface PluginSearchProvider {
    label: string;
    search: (query: string) => Promise<PluginSearchResult[]>;
    permission?: string;
}

export interface PluginQuickAction {
    id: string;
    label: string;
    icon?: string;
    keywords?: string[];
    permission?: string;
    execute: () => void | Promise<void>;
}

export interface PluginRegistryEntry {
    id: string;
    name: string;
    routes: PluginRoute[];
    navItems: PluginNavItem[];
    dashboardTiles: PluginDashboardTile[];
    extensionTiles: PluginExtensionTile[];
    settingsPanel?: PluginSettingsPanel;
    searchProvider?: PluginSearchProvider;
    quickActions?: PluginQuickAction[];
}

export const pluginRegistry: PluginRegistryEntry[] = [
    {
        id: 'todo',
        name: 'Aufgaben',
        routes: (Array.isArray(plugin_todo_0.routes) ? plugin_todo_0.routes : []) as PluginRoute[],
        navItems: (Array.isArray(plugin_todo_0.navItems) ? plugin_todo_0.navItems : []) as PluginNavItem[],
        dashboardTiles: (Array.isArray(plugin_todo_0.dashboardTiles) ? plugin_todo_0.dashboardTiles : []) as PluginDashboardTile[],
        extensionTiles: (Array.isArray(plugin_todo_0.extensionTiles) ? plugin_todo_0.extensionTiles : []) as PluginExtensionTile[],
        settingsPanel: (plugin_todo_0.settingsPanel && typeof plugin_todo_0.settingsPanel === 'object' ? plugin_todo_0.settingsPanel : undefined) as PluginSettingsPanel | undefined,
        searchProvider: (plugin_todo_0.searchProvider && typeof plugin_todo_0.searchProvider === 'object' ? plugin_todo_0.searchProvider : undefined) as PluginSearchProvider | undefined,
        quickActions: (Array.isArray(plugin_todo_0.quickActions) ? plugin_todo_0.quickActions : []) as PluginQuickAction[],
    }
];
